Typos corrected
Yuri-SVB/Great_Wall pull request #71
Opened 2024-03-28 17:08 UTC by Girelli56617

There were a few Typos on the code. So as Flat Feather asked, I corrected them

2024-03-28 17:41 UTC, MuhammadMuradG requested changes
Good catch, I left some inline comments and you need to address them please.

2024-03-28 17:41 UTC, MuhammadMuradG commented on README.md
> +    <a href="License"><img alt="Software License" src="https://img.shields.io/badge/License-MIT-brightgreen.svg?style=flat-square&logo=appveyor"></a>
Actually, this is a link to the license file, so it is not a typo.

2024-03-28 18:01 UTC, Girelli56617 commented
I corrected some more typos (this time mostly by hand) so double check it, please

2024-03-28 19:12 UTC, Yuri-SVB requested changes
Apply requested changes and add before-and-after comparison requested in README.md

2024-03-28 19:12 UTC, Yuri-SVB commented on src/greatwall/resources/knowledge/mnemonic/mnemonic.py
> +            The words to be searched, they must be a complete sentence
```suggestion
            The words to be searched. They must be a complete sentence.
```

2024-03-28 21:43 UTC, MuhammadMuradG approved these changes
It's good for me...

2024-03-28 22:48 UTC, Yuri-SVB commented on README.md
@Girelli56617 and @MuhammadMuradG, to my understanding: if the extra 'd' in 'bridghtgreen' was a typo, what was broken as a consequence of it?

2024-03-29 02:55 UTC, Girelli56617 commented on README.md
Nothing was altered by it. I just removed that because I noticed that very slight difference between the 2 hyperlinks after removing the extra <p>.

2024-03-29 03:45 UTC, MuhammadMuradG commented on README.md
Actually, the extra `d` did not break any thing because when the service fails to bring the user determined color, automatically the service uses the default color, which is `brightgreen`.

2024-03-29 13:52 UTC, Yuri-SVB submitted a review, later dismissed

2024-03-29 13:54 UTC, Yuri-SVB commented
It looks like PR is pending @Girelli56617 's signature.

2024-04-02 17:47 UTC, MuhammadMuradG requested changes
First, if you need to work on more than one issue please let each one of them in a separated PR, because the best practice is to keep each PR relating to only one issue.

Also, you need to address the conflicted files, but before you need to sign your commits that are previously submitted. 

I left some inline comments, but you need first to move the parts relating to GUI to new PR.

2024-04-02 17:47 UTC, MuhammadMuradG commented on src/greatwall/gui.py
> -
The python convention is to keep 2 blank lines before class definition.

2024-04-02 17:47 UTC, MuhammadMuradG commented on src/greatwall/gui.py
> +        self._qimage.setColorTable(colormap)
Why you added the space at the end?

2024-04-02 17:47 UTC, MuhammadMuradG commented on src/greatwall/gui.py
> -
Actually this line is to separate the context when we read the code, so, please keep this line.

2024-04-02 17:47 UTC, MuhammadMuradG commented on src/greatwall/gui.py
> +
Remove this tab please...

2024-04-02 17:47 UTC, MuhammadMuradG commented on src/greatwall/gui.py
> +        )
Keep these lines as comments please.

2024-04-02 17:47 UTC, MuhammadMuradG commented on src/greatwall/resources/knowledge/mnemonic/GUI_qt.py
> +
Keep this file as it is, this file is not related to our GUI and we will remove it in the future.

2024-04-03 03:06 UTC, closed without merging